### PR TITLE
Fix theme undefined in dialog

### LINKED ISSUE #176: Dialog fails since theme is undefined
**Describe the bug**
Theme is undefined on this line in `dialog`
https://github.com/piever/InteractBase.jl/blob/0a91fe6d605cafcb27b1b9c15d5fea568fb187da/src/input.jl#L113

Original report here:
https://github.com/JuliaGizmos/Interact.jl/issues/414

**To Reproduce**
See https://github.com/JuliaGizmos/Interact.jl/issues/414

**Expected behavior**
`theme` should be defined.

**Screenshots**
See https://github.com/JuliaGizmos/Interact.jl/issues/414

**Version info (please complete the following information):**
 - include the output of `versioninfo()` and `Pkg.status()`
 - how are you deploying the widgets? Jupyter Notebook/Lab, Juno, Blink or Mux?

**Before opening an issue**
- make sure you are on the latest release of InteractBase and try rebuilding it with `Pkg.build("InteractBase")`

**If widgets do not appear**
 - test that your WebIO is correctly installed. Make sure you're on latest release and rebuild it with `Pkg.build("WebIO")`
- try a simple code to produce a slider: `using WebIO; display(Node(:input, attributes = Dict("type" => "range")))`
- if this doesn't produce a slider, your WebIO is not installed correctly and you may wish to open an issue at WebIO rather than here,

### PR DESCRIPTION
**Pull request by mkitti**
Fix #176

### CODE REVIEW

**Review by rafaqz — APPROVED** [review]
Thanks LGTM. Must have missed those. 

The idea was to always pass around know state like the theme because getting it again from globals isnt type stable.

**Comment by mkitti** [comment]
Thanks for looking this over.

**Comment by beorostica** [comment]
We are really interested in using this feature soon for [KomaMRI.jl](https://github.com/cncastillo/KomaMRI.jl).
When would this be merged in a new version of IntectBase and updated in the julia registries?

**Comment by mkitti** [comment]
We'll need @piever to move forward. Actually, I'm not sure who has merge capabilities here.

**Comment by piever** [comment]
So, I'm happy to tag a release, but I agree that it is not ideal that I'm the only person with merging privileges here. Should I simply move this repo to JuliaGizmos? It seems like the more robust solution going forward.

cc: @travigd, @shashi, @rafaqz

**Comment by mkitti** [comment]
> Should I simply move this repo to JuliaGizmos?

I think this makes sense especially if this is not being very actively developed at the moment.

**Comment by shashi** [comment]
@piever Sounds fine to me as long as you will still retain merge privileges :)

**Comment by mkitti** [comment]
I believe it does warrant a release. Users are reporting issues with Interact.jl:
https://github.com/JuliaGizmos/Interact.jl/issues/414

**Pull request merged**
