### PR TITLE
Make rangeslider the default

### PR DESCRIPTION
**Pull request by piever**

### CODE REVIEW

**Comment by piever** [comment]
You're probably right that I should keep both, esp. as the native HTML one is actually more in line with the philosophy of the package (pure HTML widget with extra CSS for style). What do you suggest in terms of names? I'm not thrilled by `nativeslider` and `slider`. Maybe `slider` (HTML) and `rangeslider` (noUIslider) is not so bad after all, as long as the `noUIslider` is well documented.

**Comment by piever** [comment]
> Apologies I havent quite got around to dealing with the styling with all the 1.0 updates I've been doing!

No problem! Check out #89 for the layout, maybe we can coordinate efforts there.

**Comment by rafaqz** [comment]
Hah those are the exact lines I was changing.

My branch has all of that styling replaced with classes so the details are in the CSS file. Basically I'm imposing a "no styling in code" rule but I wasn't sure if everyone is on board with that.

It can easily incorporate those changes.

**Comment by piever** [comment]
> Basically I'm imposing a "no styling in code" rule but I wasn't sure if everyone is on board with that.

That's definitely a healthier approach, when you have time do make a PR potentially incorporating the fixes from @djsegal / coordinating with him!

**Comment by rafaqz** [comment]
Hopefully soon, whenever this 1.0 CI nightmare is over

Is `rangeslider` specifying that the rangeslider can have two values ie a range? then rangeslider is a good name! :)

**Comment by piever** [comment]
Yes, it can have two  or more values. Related question then: should `rangeslider` default to selecting a range then? Say `value = [extrema(vals)...]` by default?

**Comment by piever** [comment]
I've pushed a bunch of fixes to the normal slider so that now it has `orientation=:vertical` as well as support for unitful arrays and I'm getting more and more convinced to keep both (and export both).

The two questions are:
- naming: `slider` and `rangeslider` seem reasonably good
- which one gets selected for `@manipulate`

**Pull request closed without merging**
