### PR TITLE
Update to the latest Observables

### PR DESCRIPTION
**Pull request by MasonProtter**
WebIO `v0.8.19` is only compatible with Observables `v0.5`, and older versions of WebIO are broken with Observables `v0.5`, so these are the new minimum possible versions. It would be really great if we could update this to Observables v0.5 so that a bunch of other packages don't get downgraded when installing Interact.jl

### CODE REVIEW

**Comment by piever** [comment]
Can't we just add support for Observable 0.5 without removing support for anything else, i.e., combinations of older julia + older WebIO + older Observables?

**Comment by MasonProtter** [comment]
The previous version of WebIO erroneously added support for Observables 0.5 even though it didn't work, so `pkg` would let someone install WebIO 0.8.18 and Observables 0.5 which would be bad. Not sure how multiversioning would work here, maybe we could do
```
WebIO = "0.3,0.4,0.5,0.6,0.7,0.8.19"
```
?

**Comment by piever** [comment]
Yes, that seems fine! Though I imagine ideally non-working versions of WebIO should be yanked from the registry.

**Comment by MasonProtter** [comment]
Okay, I've have WebIO 0.8.18 removed from the registry, and updated the PR accordingly.

**Comment by MasonProtter** [comment]
@piever In light of the CI issues here, my advice is to just drop support for Julia 1.0. It's no longer LTS, and if people really want to use 1.0, then they need to use old versions of Interact anyways because Observables and WebIO have dropped support for pre-1.6 julia support. 

What would you prefer to do here? I really want to move forward with this, because currently Interact is holding back a bunch of other packages from updating on my system due to it's outdated Observables.jl deps.

**Comment by piever** [comment]
Yes, it turns out julia 1.0 doesn't support yanking, so there isn't a good way of supporting it... I'm bumping the julia requirement in #172. If CI passes, I can just merge and tag.

**Pull request merged**
