### PR TITLE
Typed widgets

### PR DESCRIPTION
**Pull request by piever**

### CODE REVIEW

**Comment by shashi** [comment]
I think there's no need to use `Widget{Val{symbol}}`, you can just use `Widget{symbol}`. Generally avoiding nested type parameters is extremely good for compilation time.

I got a method error while trying to set the height of a widget using `style`. But to be fair that's also a problem in Scope (ref https://github.com/JuliaGizmos/WebIO.jl/issues/132).

**Comment by piever** [comment]
I was coming to the same conclusion. There was a feature request to have different types for different widgets for dispatch, but maybe it's not worth it the extra compilation time. If somebody really needs to dispatch on widget type that they can always do:

```
f(Val{widgettype(ui)}(), ui, ...)
```

I'll look into the style issue, I think passing `style` when creating the widget should work, will check later.

**Comment by piever** [comment]
I'm not sure I understand your remark on the nested widget type: so far `ui.typ` will be of type `Val{:slider}`, but the type parameter is a symbol (meaning `slider(1:100)::Widget{:slider}`). Is that also problematic for compilation times? I'm still not 100% sure whether I prefer:

```julia
mutable struct Widget
    typ::Symbol
    node::Union{WebIO.Scope, WebIO.Node}
    primary_scope::WebIO.Scope
    primary_obs::Observable
end
```

or:

```julia
mutable struct Widget{T}
    typ::Val{T}
    node::Union{WebIO.Scope, WebIO.Node}
    primary_scope::WebIO.Scope
    primary_obs::Observable
end
```

What do you think?

**Comment by rafaqz** [comment]
Dispatching on Val{widgettype()} is fine, but pretty obscure.

I don't understand what the overheads are for just having one type for each widget instead of the parametric type, and just dispatching on AbstractWidget. Is it duplicating the fields???

This seems like a case for old-school inheritance. Having a Type for each widget would be totally painless. If you're avoiding good architecture for compilation time something is really wrong.

**Comment by shashi** [comment]
I just meant

```julia
mutable struct Widget{type}
    node::Union{WebIO.Scope, WebIO.Node}
    primary_scope::WebIO.Scope
    primary_obs::Observable
end
```

Where typ is a symbol. There's no need to save it as a field as well. I disagree that a different type for each widget is good architecture, it just leads to a of redundant code.

Just curious why do we need to store `primary_scope`.

**Comment by rafaqz** [comment]
Ok there are some crossed wires here, my aplogies!

@piever just told me in the other thread I would have to use `f(Val{widgettype(ui)}(), ui, ...)` for dispatch  on widget type because symbols in the type take too long to compile, coming from this thread. I can't dispute that but it seems like a troubling design choice to me.

I also agree that a different type for each widget isn't the best architecture, but its better than dispatching with functions! (and it would only take 10 extra lines or so really)

Widgeth{T} where T is a symbol is perfect. It doesn't need a field, just the type system. But piever was saying he would remove it completely, so now I'm confused about what is happening.

**Comment by shashi** [comment]
Ah ok, I was just replying to this thread, sorry.

@piever I didn't mean to raise as huge alarm about the issue, just suggesting we could reduce one level of nesting :)

```julia
mutable struct Widget{typ}
    node::Union{WebIO.Scope, WebIO.Node}
    primary_scope::WebIO.Scope
    primary_obs::Observable
end
```

would be OK.

**Comment by rafaqz** [comment]
No problem, me either. I was just shuddering at the idea of having to use functions in the type for dispatch, or worse, have `if` blocks messing with my one-line function policy...

**Comment by piever** [comment]
Ups, somehow I completely missed that I could just pass a symbol as a parameter type without any `Val` trickery: that's clearly the best solution, sorry about the confusion!

> Just curious why do we need to store `primary_scope`.

I need to have a distinct `node` (to be displayed) and `primary_scope` (associated scope) because Bulma wants every widget to be wrapped in a `<div class="field"></div>` for the automatic form layout to work and it doesn't work if the `div` is withing the scope. This separation allows me more freedom in wrapping scopes. Storing it is generally useful to still access `Observables` that are not primary, though that's not yet a documented feature.

**Comment by shashi** [comment]
Interact takes too long to show the first `@manipulate` on 1.0, I suspect this change has something to do with it. :( I'll investigate this at some point and we may have to crack down on the offender.

**Pull request merged**
